# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: driver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'driver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\x0flastmile.driver\x1a\x1bgoogle/protobuf/empty.proto\"A\n\x05Route\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x13\n\x0bstation_ids\x18\x02 \x03(\t\x12\x11\n\twaypoints\x18\x03 \x03(\t\"d\n\rDriverProfile\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x12\n\nvehicle_no\x18\x05 \x01(\t\"H\n\x15RegisterDriverRequest\x12/\n\x07profile\x18\x01 \x01(\x0b\x32\x1e.lastmile.driver.DriverProfile\"7\n\x16RegisterDriverResponse\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\"|\n\x12\x44riverRouteRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12%\n\x05route\x18\x02 \x01(\x0b\x32\x16.lastmile.driver.Route\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x17\n\x0f\x61vailable_seats\x18\x04 \x01(\x05\"!\n\x13\x44riverRouteResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\xb2\x01\n\x0eLocationUpdate\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\nstation_id\x18\x06 \x01(\t\x12\x17\n\x0f\x61vailable_seats\x18\x07 \x01(\x05\x12\x13\n\x0b\x64\x65stination\x18\x08 \x01(\t\x12\x0e\n\x06\x65ta_ms\x18\t \x01(\x03\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xcf\x02\n\rDriverService\x12\x61\n\x0eRegisterDriver\x12&.lastmile.driver.RegisterDriverRequest\x1a\'.lastmile.driver.RegisterDriverResponse\x12X\n\x0bUpdateRoute\x12#.lastmile.driver.DriverRouteRequest\x1a$.lastmile.driver.DriverRouteResponse\x12I\n\x0eStreamLocation\x12\x1f.lastmile.driver.LocationUpdate\x1a\x14.lastmile.driver.Ack(\x01\x12\x36\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x14.lastmile.driver.AckB\x13Z\x11lastmile/driverpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'driver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021lastmile/driverpb'
  _globals['_ROUTE']._serialized_start=62
  _globals['_ROUTE']._serialized_end=127
  _globals['_DRIVERPROFILE']._serialized_start=129
  _globals['_DRIVERPROFILE']._serialized_end=229
  _globals['_REGISTERDRIVERREQUEST']._serialized_start=231
  _globals['_REGISTERDRIVERREQUEST']._serialized_end=303
  _globals['_REGISTERDRIVERRESPONSE']._serialized_start=305
  _globals['_REGISTERDRIVERRESPONSE']._serialized_end=360
  _globals['_DRIVERROUTEREQUEST']._serialized_start=362
  _globals['_DRIVERROUTEREQUEST']._serialized_end=486
  _globals['_DRIVERROUTERESPONSE']._serialized_start=488
  _globals['_DRIVERROUTERESPONSE']._serialized_end=521
  _globals['_LOCATIONUPDATE']._serialized_start=524
  _globals['_LOCATIONUPDATE']._serialized_end=702
  _globals['_ACK']._serialized_start=704
  _globals['_ACK']._serialized_end=721
  _globals['_DRIVERSERVICE']._serialized_start=724
  _globals['_DRIVERSERVICE']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
