# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import driver_pb2 as driver__pb2
from services.common_lib.protos_generated import driver_pb2 as driver__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDriver = channel.unary_unary(
                '/lastmile.driver.DriverService/RegisterDriver',
                request_serializer=driver__pb2.RegisterDriverRequest.SerializeToString,
                response_deserializer=driver__pb2.RegisterDriverResponse.FromString,
                _registered_method=True)
        self.UpdateRoute = channel.unary_unary(
                '/lastmile.driver.DriverService/UpdateRoute',
                request_serializer=driver__pb2.DriverRouteRequest.SerializeToString,
                response_deserializer=driver__pb2.DriverRouteResponse.FromString,
                _registered_method=True)
        self.StreamLocation = channel.stream_unary(
                '/lastmile.driver.DriverService/StreamLocation',
                request_serializer=driver__pb2.LocationUpdate.SerializeToString,
                response_deserializer=driver__pb2.Ack.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/lastmile.driver.DriverService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=driver__pb2.Ack.FromString,
                _registered_method=True)


class DriverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLocation(self, request_iterator, context):
        """streaming locations from driver -> server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDriver,
                    request_deserializer=driver__pb2.RegisterDriverRequest.FromString,
                    response_serializer=driver__pb2.RegisterDriverResponse.SerializeToString,
            ),
            'UpdateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRoute,
                    request_deserializer=driver__pb2.DriverRouteRequest.FromString,
                    response_serializer=driver__pb2.DriverRouteResponse.SerializeToString,
            ),
            'StreamLocation': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLocation,
                    request_deserializer=driver__pb2.LocationUpdate.FromString,
                    response_serializer=driver__pb2.Ack.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=driver__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lastmile.driver.DriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lastmile.driver.DriverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.driver.DriverService/RegisterDriver',
            driver__pb2.RegisterDriverRequest.SerializeToString,
            driver__pb2.RegisterDriverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.driver.DriverService/UpdateRoute',
            driver__pb2.DriverRouteRequest.SerializeToString,
            driver__pb2.DriverRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLocation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/lastmile.driver.DriverService/StreamLocation',
            driver__pb2.LocationUpdate.SerializeToString,
            driver__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.driver.DriverService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            driver__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
