# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x11lastmile.location\x1a\x1bgoogle/protobuf/empty.proto\"\x9b\x01\n\x0e\x44riverLocation\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\x12\n\n\x02ts\x18\x04 \x01(\x03\x12\x12\n\nstation_id\x18\x05 \x01(\t\x12\x17\n\x0f\x61vailable_seats\x18\x06 \x01(\x05\x12\x0e\n\x06\x65ta_ms\x18\x07 \x01(\x03\x12\x13\n\x0b\x64\x65stination\x18\x08 \x01(\t\"W\n\x0eProximityEvent\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x12\n\nstation_id\x18\x02 \x01(\t\x12\x12\n\ndistance_m\x18\x03 \x01(\x01\x12\n\n\x02ts\x18\x04 \x01(\x03\x32\xf5\x01\n\x0fLocationService\x12K\n\x0eReportLocation\x12!.lastmile.location.DriverLocation\x1a\x16.google.protobuf.Empty\x12[\n\x0fStreamProximity\x12!.lastmile.location.DriverLocation\x1a!.lastmile.location.ProximityEvent(\x01\x30\x01\x12\x38\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x15Z\x13lastmile/locationpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023lastmile/locationpb'
  _globals['_DRIVERLOCATION']._serialized_start=67
  _globals['_DRIVERLOCATION']._serialized_end=222
  _globals['_PROXIMITYEVENT']._serialized_start=224
  _globals['_PROXIMITYEVENT']._serialized_end=311
  _globals['_LOCATIONSERVICE']._serialized_start=314
  _globals['_LOCATIONSERVICE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
