# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from services.common_lib.protos_generated import matching_pb2 as matching__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in matching_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MatchingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindMatches = channel.unary_unary(
                '/lastmile.matching.MatchingService/FindMatches',
                request_serializer=matching__pb2.MatchRequest.SerializeToString,
                response_deserializer=matching__pb2.MatchResponse.FromString,
                _registered_method=True)
        self.StreamMatches = channel.stream_stream(
                '/lastmile.matching.MatchingService/StreamMatches',
                request_serializer=matching__pb2.MatchRequest.SerializeToString,
                response_deserializer=matching__pb2.MatchResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/lastmile.matching.MatchingService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=matching__pb2.MatchResponse.FromString,
                _registered_method=True)


class MatchingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMatches(self, request_iterator, context):
        """streaming API for proposals and responses (optional)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatchingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindMatches': grpc.unary_unary_rpc_method_handler(
                    servicer.FindMatches,
                    request_deserializer=matching__pb2.MatchRequest.FromString,
                    response_serializer=matching__pb2.MatchResponse.SerializeToString,
            ),
            'StreamMatches': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMatches,
                    request_deserializer=matching__pb2.MatchRequest.FromString,
                    response_serializer=matching__pb2.MatchResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=matching__pb2.MatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lastmile.matching.MatchingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lastmile.matching.MatchingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatchingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.matching.MatchingService/FindMatches',
            matching__pb2.MatchRequest.SerializeToString,
            matching__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMatches(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lastmile.matching.MatchingService/StreamMatches',
            matching__pb2.MatchRequest.SerializeToString,
            matching__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lastmile.matching.MatchingService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            matching__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
