# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matching.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'matching.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ematching.proto\x12\x11lastmile.matching\x1a\x1bgoogle/protobuf/empty.proto\"n\n\x0eMatchCandidate\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x10\n\x08rider_id\x18\x02 \x01(\t\x12\x12\n\nstation_id\x18\x03 \x01(\t\x12\x0e\n\x06\x65ta_ms\x18\x04 \x01(\x03\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\"T\n\x0cMatchRequest\x12\x12\n\nstation_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\x12\x11\n\trider_ids\x18\x03 \x03(\t\x12\n\n\x02ts\x18\x04 \x01(\x03\"B\n\rMatchResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07trip_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t2\xff\x01\n\x0fMatchingService\x12P\n\x0b\x46indMatches\x12\x1f.lastmile.matching.MatchRequest\x1a .lastmile.matching.MatchResponse\x12V\n\rStreamMatches\x12\x1f.lastmile.matching.MatchRequest\x1a .lastmile.matching.MatchResponse(\x01\x30\x01\x12\x42\n\x06Health\x12\x16.google.protobuf.Empty\x1a .lastmile.matching.MatchResponseB\x15Z\x13lastmile/matchingpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matching_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023lastmile/matchingpb'
  _globals['_MATCHCANDIDATE']._serialized_start=66
  _globals['_MATCHCANDIDATE']._serialized_end=176
  _globals['_MATCHREQUEST']._serialized_start=178
  _globals['_MATCHREQUEST']._serialized_end=262
  _globals['_MATCHRESPONSE']._serialized_start=264
  _globals['_MATCHRESPONSE']._serialized_end=330
  _globals['_MATCHINGSERVICE']._serialized_start=333
  _globals['_MATCHINGSERVICE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
