# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x15lastmile.notification\x1a\x1bgoogle/protobuf/empty.proto\"e\n\x0cNotification\x12\r\n\x05to_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x0c\n\x04meta\x18\x05 \x01(\t\x12\n\n\x02ts\x18\x06 \x01(\x03\"&\n\tNotifyAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x8a\x02\n\x13NotificationService\x12M\n\x04Send\x12#.lastmile.notification.Notification\x1a .lastmile.notification.NotifyAck\x12`\n\x13StreamNotifications\x12#.lastmile.notification.Notification\x1a .lastmile.notification.NotifyAck(\x01\x30\x01\x12\x42\n\x06Health\x12\x16.google.protobuf.Empty\x1a .lastmile.notification.NotifyAckB\x19Z\x17lastmile/notificationpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027lastmile/notificationpb'
  _globals['_NOTIFICATION']._serialized_start=74
  _globals['_NOTIFICATION']._serialized_end=175
  _globals['_NOTIFYACK']._serialized_start=177
  _globals['_NOTIFYACK']._serialized_end=215
  _globals['_NOTIFICATIONSERVICE']._serialized_start=218
  _globals['_NOTIFICATIONSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
