# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rider.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brider.proto\x12\x0elastmile.rider\x1a\x1bgoogle/protobuf/empty.proto\"N\n\x0cRiderProfile\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"E\n\x14RegisterRiderRequest\x12-\n\x07profile\x18\x01 \x01(\x0b\x32\x1c.lastmile.rider.RiderProfile\"5\n\x15RegisterRiderResponse\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\"s\n\x0cRiderRequest\x12\x10\n\x08rider_id\x18\x01 \x01(\t\x12\x12\n\nstation_id\x18\x02 \x01(\t\x12\x14\n\x0c\x61rrival_time\x18\x03 \x01(\x03\x12\x13\n\x0b\x64\x65stination\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"/\n\rRiderResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x32\xc5\x02\n\x0cRiderService\x12\\\n\rRegisterRider\x12$.lastmile.rider.RegisterRiderRequest\x1a%.lastmile.rider.RegisterRiderResponse\x12L\n\rRequestPickup\x12\x1c.lastmile.rider.RiderRequest\x1a\x1d.lastmile.rider.RiderResponse\x12H\n\tTrackRide\x12\x1c.lastmile.rider.RiderRequest\x1a\x1d.lastmile.rider.RiderResponse\x12?\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x1d.lastmile.rider.RiderResponseB\x12Z\x10lastmile/riderpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rider_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020lastmile/riderpb'
  _globals['_RIDERPROFILE']._serialized_start=60
  _globals['_RIDERPROFILE']._serialized_end=138
  _globals['_REGISTERRIDERREQUEST']._serialized_start=140
  _globals['_REGISTERRIDERREQUEST']._serialized_end=209
  _globals['_REGISTERRIDERRESPONSE']._serialized_start=211
  _globals['_REGISTERRIDERRESPONSE']._serialized_end=264
  _globals['_RIDERREQUEST']._serialized_start=266
  _globals['_RIDERREQUEST']._serialized_end=381
  _globals['_RIDERRESPONSE']._serialized_start=383
  _globals['_RIDERRESPONSE']._serialized_end=430
  _globals['_RIDERSERVICE']._serialized_start=433
  _globals['_RIDERSERVICE']._serialized_end=758
# @@protoc_insertion_point(module_scope)
