# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: station.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'station.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstation.proto\x12\x10lastmile.station\x1a\x1bgoogle/protobuf/empty.proto\"\\\n\x07Station\x12\x12\n\nstation_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lng\x18\x04 \x01(\x01\x12\x15\n\rnearby_places\x18\x05 \x03(\t\"$\n\x0eStationRequest\x12\x12\n\nstation_id\x18\x01 \x01(\t\")\n\x12StationListRequest\x12\x13\n\x0bstation_ids\x18\x01 \x03(\t\"=\n\x0fStationResponse\x12*\n\x07station\x18\x01 \x01(\x0b\x32\x19.lastmile.station.Station\"B\n\x13StationListResponse\x12+\n\x08stations\x18\x01 \x03(\x0b\x32\x19.lastmile.station.Station2\x85\x02\n\x0eStationService\x12Q\n\nGetStation\x12 .lastmile.station.StationRequest\x1a!.lastmile.station.StationResponse\x12[\n\x0cListStations\x12$.lastmile.station.StationListRequest\x1a%.lastmile.station.StationListResponse\x12\x43\n\x06Health\x12\x16.google.protobuf.Empty\x1a!.lastmile.station.StationResponseB\x14Z\x12lastmile/stationpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'station_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022lastmile/stationpb'
  _globals['_STATION']._serialized_start=64
  _globals['_STATION']._serialized_end=156
  _globals['_STATIONREQUEST']._serialized_start=158
  _globals['_STATIONREQUEST']._serialized_end=194
  _globals['_STATIONLISTREQUEST']._serialized_start=196
  _globals['_STATIONLISTREQUEST']._serialized_end=237
  _globals['_STATIONRESPONSE']._serialized_start=239
  _globals['_STATIONRESPONSE']._serialized_end=300
  _globals['_STATIONLISTRESPONSE']._serialized_start=302
  _globals['_STATIONLISTRESPONSE']._serialized_end=368
  _globals['_STATIONSERVICE']._serialized_start=371
  _globals['_STATIONSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
