# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntrip.proto\x12\rlastmile.trip\x1a\x1bgoogle/protobuf/empty.proto\"\xb8\x01\n\x04Trip\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\x12\x11\n\trider_ids\x18\x03 \x03(\t\x12\x16\n\x0eorigin_station\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x12\n\nstart_time\x18\x07 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x08 \x01(\x03\x12\x16\n\x0eseats_reserved\x18\t \x01(\x05\"6\n\x11\x43reateTripRequest\x12!\n\x04trip\x18\x01 \x01(\x0b\x32\x13.lastmile.trip.Trip\"A\n\x12\x43reateTripResponse\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\"6\n\x11UpdateTripRequest\x12!\n\x04trip\x18\x01 \x01(\x0b\x32\x13.lastmile.trip.Trip\" \n\x12UpdateTripResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"!\n\x0eGetTripRequest\x12\x0f\n\x07trip_id\x18\x01 \x01(\t\"4\n\x0fGetTripResponse\x12!\n\x04trip\x18\x01 \x01(\x0b\x32\x13.lastmile.trip.Trip2\xc2\x02\n\x0bTripService\x12Q\n\nCreateTrip\x12 .lastmile.trip.CreateTripRequest\x1a!.lastmile.trip.CreateTripResponse\x12Q\n\nUpdateTrip\x12 .lastmile.trip.UpdateTripRequest\x1a!.lastmile.trip.UpdateTripResponse\x12H\n\x07GetTrip\x12\x1d.lastmile.trip.GetTripRequest\x1a\x1e.lastmile.trip.GetTripResponse\x12\x43\n\x06Health\x12\x16.google.protobuf.Empty\x1a!.lastmile.trip.CreateTripResponseB\x11Z\x0flastmile/trippbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017lastmile/trippb'
  _globals['_TRIP']._serialized_start=59
  _globals['_TRIP']._serialized_end=243
  _globals['_CREATETRIPREQUEST']._serialized_start=245
  _globals['_CREATETRIPREQUEST']._serialized_end=299
  _globals['_CREATETRIPRESPONSE']._serialized_start=301
  _globals['_CREATETRIPRESPONSE']._serialized_end=366
  _globals['_UPDATETRIPREQUEST']._serialized_start=368
  _globals['_UPDATETRIPREQUEST']._serialized_end=422
  _globals['_UPDATETRIPRESPONSE']._serialized_start=424
  _globals['_UPDATETRIPRESPONSE']._serialized_end=456
  _globals['_GETTRIPREQUEST']._serialized_start=458
  _globals['_GETTRIPREQUEST']._serialized_end=491
  _globals['_GETTRIPRESPONSE']._serialized_start=493
  _globals['_GETTRIPRESPONSE']._serialized_end=545
  _globals['_TRIPSERVICE']._serialized_start=548
  _globals['_TRIPSERVICE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
