# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\rlastmile.user\x1a\x1bgoogle/protobuf/empty.proto\"X\n\x0bUserProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t\"T\n\x13RegisterUserRequest\x12+\n\x07profile\x18\x01 \x01(\x0b\x32\x1a.lastmile.user.UserProfile\x12\x10\n\x08password\x18\x02 \x01(\t\"B\n\x14RegisterUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\r\n\x05token\x18\x03 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\">\n\x0fGetUserResponse\x12+\n\x07profile\x18\x01 \x01(\x0b\x32\x1a.lastmile.user.UserProfile2\xb6\x02\n\x0bUserService\x12W\n\x0cRegisterUser\x12\".lastmile.user.RegisterUserRequest\x1a#.lastmile.user.RegisterUserResponse\x12\x42\n\x05Login\x12\x1b.lastmile.user.LoginRequest\x1a\x1c.lastmile.user.LoginResponse\x12H\n\x07GetUser\x12\x1d.lastmile.user.GetUserRequest\x1a\x1e.lastmile.user.GetUserResponse\x12@\n\x06Health\x12\x16.google.protobuf.Empty\x1a\x1e.lastmile.user.GetUserResponseB\x11Z\x0flastmile/userpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017lastmile/userpb'
  _globals['_USERPROFILE']._serialized_start=58
  _globals['_USERPROFILE']._serialized_end=146
  _globals['_REGISTERUSERREQUEST']._serialized_start=148
  _globals['_REGISTERUSERREQUEST']._serialized_end=232
  _globals['_REGISTERUSERRESPONSE']._serialized_start=234
  _globals['_REGISTERUSERRESPONSE']._serialized_end=300
  _globals['_LOGINREQUEST']._serialized_start=302
  _globals['_LOGINREQUEST']._serialized_end=349
  _globals['_LOGINRESPONSE']._serialized_start=351
  _globals['_LOGINRESPONSE']._serialized_end=398
  _globals['_GETUSERREQUEST']._serialized_start=400
  _globals['_GETUSERREQUEST']._serialized_end=433
  _globals['_GETUSERRESPONSE']._serialized_start=435
  _globals['_GETUSERRESPONSE']._serialized_end=497
  _globals['_USERSERVICE']._serialized_start=500
  _globals['_USERSERVICE']._serialized_end=810
# @@protoc_insertion_point(module_scope)
